plugin:
  onEnable:
    - "§8+-----------------------------------------+"
    - "            §6>>  §2Carton§aBox"
    - "            §6>>  §aEnabling"
    - "§8+-----------------------------------------+"

  onDisable:
    - "§8+-----------------------------------------+"
    - "            §6>>  §2Carton§aBox"
    - "            §6>>  §cDisabling"
    - "§8+-----------------------------------------+"

scotch:
  skull:
    name: "Tape (white)" #Useless because this will be renamed later
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzIxOTc2MmY5M2I3NzJlMzU4ZGE5OTJkYTIyYmM1YTUxYmU1YWJjN2JiOGFmZTEzNDI0MjhiMjQ5NTM2YzgifX19"

  name: "&8Scotch"
  lore:
    - "&3Tape It!"
    - "&3Put a block with inventory"
    - "&3in a box and close it with"
    - "&3a... Scotch!"

box:
  skull:
    name: "Cardboard Box" #Useless because this will be renamed later
    texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDk2NDk2ODVjM2FkZmJkN2U2NWY5OTA1ZjcwNWZjNTY3NGJlNGM4ZWE1YTVkNmY1ZjcyZThlYmFkMTkyOSJ9fX0="

  name: "&8CartboardBox of %container_name%"
  lore:
    - "&3A box!"