name: Cartonbox
version: '${project.version}'
main: me.devwhitefox.cartonbox.Cartonbox
api-version: 1.18
authors: [ DevWhiteFox ]
description: This plugin promises to take a block with an inventory and carry it around and then place it elsewhere.
